CREATE TABLE IF NOT EXISTS student(
student_id SERIAL PRIMARY KEY,name VARCHAR(20),major VARCHAR(20))

CREATE TABLE IF NOT EXISTS artists(id SERIAL PRIMARY KEY,Name VARCHAR);

SELECT *
FROM artists;

CREATE TABLE IF NOT EXISTS city(id SERIAL PRIMARY KEY,name VARCHAR(30),	population INT
);

SELECT *
FROM city;


DROP TABLE invoices;
CREATE TABLE IF NOT EXISTS invoices(
id SERIAL PRIMARY KEY,
customerId INT,
date DATE,
address VARCHAR(100),
city VARCHAR(40),
state VARCHAR(20),
country VARCHAR(20),
postalcode VARCHAR(20),
total REAL
);

SELECT *
FROM invoices;